"""error column in photo

Revision ID: 705a3b93c81d
Revises: cd80bae1130a
Create Date: 2019-07-03 00:57:32.225234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705a3b93c81d'
down_revision = 'cd80bae1130a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('photo', sa.Column('error', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'error')
    op.drop_column('photo', 'deleted')
    # ### end Alembic commands ###
