"""country in photo

Revision ID: 7833d10dc086
Revises: 705a3b93c81d
Create Date: 2019-07-03 01:07:59.916678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7833d10dc086'
down_revision = '705a3b93c81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('country', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'country')
    # ### end Alembic commands ###
